---
title: "Gov 50 Final Project"
author: "Kelly Olmos"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---
```{r}
read.csv('acgr-lea-sy2019-20-long.csv')
read.csv('2020 November General Election - Turnout Rates.csv')
```



## Project thoughts

State your research question.

My research question aims at investigating one dimension of the question of whether public education quality affects voter turnout. To investigate this question at the quantitative level, I have decided to choose one indicator of public school (K-12) quality, graduation rates to investigate its correlation with the voter turnout in the states. My hypothesis is that higher graduation rates are correlated with higher voter turnout rates.

The explanatory variables of interest from my data set is `RATE` which provides the graduation rate from K-12 public schooling. I would have to aggregate the data of this variable of all the counties to get an average graduation rate for the state so that I can investigate its correlation to state by state voter turnout. 

The outcome variable is `X.4` which is the VEP Turnout Rate in the 2020 November General Election data set. This variable is measured by finding the proportion of voting eligible persons who voted in the 2020 general election. 

A strong positive correlation between `RATE` and `X.4` would provide support to my hypothesis whereas a lack of correlation or an outright inverse correlation would disprove my hypothesis
